spring.application.name=tour-planner

spring.datasource.url=jdbc:postgresql://<db host>:5432/tourdb
spring.datasource.username=<insert db user>
spring.datasource.password=<insert db password>
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=none

spring.jackson.property-naming-strategy=SNAKE_CASE

ors.url=https://api.openrouteservice.org
ors.api-key=<insert api key>

security.jwt.secret=<insert jwt secret>
# in ms
security.jwt.expiration=1800000
