services:
  db:
    image: postgis/postgis:16-3.5
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTRGES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - tour_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  app:
    build:
     context: ./backend
     dockerfile: Dockerfile
     target: live
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
      
  ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: live
    restart: unless-stopped
    env_file:
      - ./env/.env
    ports:
      - "8080:80"
    depends_on:
      - app

volumes:
  tour_data: