spring.application.name=tour-planner

spring.datasource.url=jdbc:postgresql://localhost:5432/worker
spring.datasource.username=worker
spring.datasource.password=secret123
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=none

spring.jackson.property-naming-strategy=SNAKE_CASE

ors.url=https://api.openrouteservice.org
ors.api-key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjMwNGMyZWRiZmI0ZTRkZmI4NzcyNzM4YTQ3YTkwZTU2IiwiaCI6Im11cm11cjY0In0=

security.jwt.secret=58d2454cb577a09fddcd51252ecc7f6a9e07ca415a65940c8e0585baa3fcf619
security.jwt.expiration=86400000
