spring.application.name=tour-planner

ors.url=https://api.openrouteservice.org
ors.api-key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjMwNGMyZWRiZmI0ZTRkZmI4NzcyNzM4YTQ3YTkwZTU2IiwiaCI6Im11cm11cjY0In0=
